# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Create one single job
# This job performs all necessary checks
jobs:
  build:
    # Use the latest version of Ubuntu on Microsoft Azure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Performs all actions on different versions of Python
        python-version: ["3.10"]
    # Define the workflow steps
    steps:
    # Checkout the code of the repository
        - name: Check out Repository Code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        # # Install pip
        # - name: Install Pip
        #   if: always()
        #   run: |
        #     pip install -U pip
        # # Install poetry
        # - name: Install Poetry
        #   if: always()
        #   uses: abatilo/actions-poetry@v2.0.0
        #   with:
        #     poetry-version: 1.1.8    

        # Run src/myDBMS.py to determine if errors exist

        # - name: Run src/myDBMS.py
        #   if: always()
        #   run:  |
        #     python3 src/myDBMS.py

        # Run GatorGrader: see config/gatorgrade.yml
        - name: Run GatorGrader with GatorGrade
          if: always()
          run:  |
            pip install gatorgrade
            gatorgrade --config config/gatorgrade.yml
